[package]
name = "shdel"
version = "0.1.0"
description = "Delete data from shell history file(s)."
authors = ["xTeKc"]
edition = "2021"

[[bin]]
name = "shdel"
path = "src/bin/shdel.rs"

[dependencies]
ansi_term = "0.12.1"
pico-args = "0.5.0"