[package]
name = "shelldel"
version = "0.1.0"
edition = "2021"

[dependencies]
ansi_term = "0.12.1"
clap = { version = "*", features = ["derive"] }

#resolver = "2"

#[profile.release]
#lto = "thin"
#codegen-units = 1