name: CI

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
          override: true

      - name: Run `cargo fmt`
        uses: actions-rs/cargo@v1
        with:
          command: fmt

      - name: Run `cargo clippy`
        uses: actions-rs/cargo@v1
        with:
          command: clippy

      - name: Run `cargo check`
        uses: actions-rs/cargo@v1
        with:
          command: check